config/routes.rb
Dashboard::Application.routes.draw do
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'  

   root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def show
  end
  
  def create
  end
  
  def update
  end
  
  def destrou
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Dashboard"
  end
  
  def contact
    @title = "Contact"
  end
    
  def help
    @title = "Help"
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def new
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "OrionVm"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li>BLARH im a footer</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("logo.png", :alt => "Sample App", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %> | OrionVm</title>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag :application %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact us by looking up into the sky and finding the OrionVm cloud
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  This is the help page... gtfo for now
</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>
  This is the home page for the
  <a href="http://orionvm.com.au/">OrionVm</a>
  dashboard application.
</p>
<table>
  <tr>
    <td>Service</td>
    <td><%= Time.now.strftime("%d/%m/%Y") %></td>
    <td><%= (Time.now - 1.days).strftime("%d/%m/%Y") %></td>
    <td><%= (Time.now - 2.days).strftime("%d/%m/%Y") %></td>
    <td><%= (Time.now - 3.days).strftime("%d/%m/%Y") %></td>
    <td><%= (Time.now - 4.days).strftime("%d/%m/%Y") %></td>
    <td><%= (Time.now - 5.days).strftime("%d/%m/%Y") %></td>
  </tr>
</table>
<ul>
  <li>Icon Ledgend here</li>
</ul>